### ISSUE TITLE
php7.4 环境安装到最后一步报错

### ISSUE THREAD

**Issue by m00nfly** [bs-community/blessing-skin-server#130]
## The Problem 问题描述
php7.4 + nginx + mysql 环境下安装，setup 到最后一步 finsh 时报错，无法完成安装；
开启debug模式后，显示下面的报错信息；
我尝试按报错提示将
`vendor/symfony/console/Helper/QuestionHelper.php:118` 中的`STDIN`修改成了`'STDIN' `后又在 `$ret = fgets($inputStream, 4096)` 出现了报错；
看起来是从 STDIN 读取有问题，不知道如何解决了；

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):
`blessing-skin-server-5.0.0-beta.3.zip`

- PHP 版本 (Version of PHP):
`PHP 7.4.1 (cli) (built: Jan  2 2020 01:30:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies`

- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):
`nginx version: nginx/1.16.1`

- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):
`Safrai`
`https://mc.moonfly.net:8443/setup/finish`

## Error Message 错误信息
**laravel-2020-02-03.log**
`[2020-02-03 09:45:57] production.ERROR: Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) {"exception":"[object] (ErrorException(code: 0): Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) at /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Helper/QuestionHelper.php:118)
[stacktrace]
#0 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Helper/QuestionHelper.php(118): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Helper/QuestionHelper.php(81): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk()
#2 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Style/SymfonyStyle.php(360): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask()
#3 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Style/SymfonyStyle.php(288): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion()
#4 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(385): Symfony\\Component\\Console\\Style\\SymfonyStyle->confirm()
#5 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(29): Illuminate\\Console\\Command->confirm()
#6 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php(76): Illuminate\\Foundation\\Console\\KeyGenerateCommand->confirmToProceed()
#7 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php(45): Illuminate\\Foundation\\Console\\KeyGenerateCommand->setKeyInEnvironmentFile()
#8 [internal function]: Illuminate\\Foundation\\Console\\KeyGenerateCommand->handle()
#9 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#10 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#14 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call()
#15 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#16 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run()
#17 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run()
#18 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#19 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#20 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#21 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Application.php(185): Illuminate\\Console\\Application->run()
#22 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\\Console\\Application->call()
#23 /usr/home/wwwroot/mc-skin-server/app/Http/Controllers/SetupController.php(116): Illuminate\\Foundation\\Console\\Kernel->call()
#24 [internal function]: App\\Http\\Controllers\\SetupController->finish()
#25 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#26 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#27 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#28 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#29 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#30 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#31 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/CheckInstallation.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckInstallation->handle()
#33 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/RedirectToSetup.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RedirectToSetup->handle()
#35 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/ForbiddenIE.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ForbiddenIE->handle()
#37 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#39 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#41 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#49 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#51 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#53 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/DetectLanguagePrefer.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#56 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#58 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#59 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#61 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#63 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#65 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#66 /usr/home/wwwroot/mc-skin-server/public/index.php(48): Illuminate\\Foundation\\Http\\Kernel->handle()
#67 {main}
"}`

**按提示修改 STDIN 为 ‘STDIN’ 后的报错日志**
`[2020-02-03 09:50:39] production.ERROR: fgets() expects parameter 1 to be resource, string given {"exception":"[object] (ErrorException(code: 0): fgets() expects parameter 1 to be resource, string given at /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Helper/QuestionHelper.php:135)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Helper/QuestionHelper.php(135): fgets()
#2 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Helper/QuestionHelper.php(81): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk()
#3 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Style/SymfonyStyle.php(360): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask()
#4 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Style/SymfonyStyle.php(288): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion()
#5 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(385): Symfony\\Component\\Console\\Style\\SymfonyStyle->confirm()
#6 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(29): Illuminate\\Console\\Command->confirm()
#7 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php(76): Illuminate\\Foundation\\Console\\KeyGenerateCommand->confirmToProceed()
#8 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php(45): Illuminate\\Foundation\\Console\\KeyGenerateCommand->setKeyInEnvironmentFile()
#9 [internal function]: Illuminate\\Foundation\\Console\\KeyGenerateCommand->handle()
#10 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#11 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#15 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call()
#16 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#17 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run()
#18 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run()
#19 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#20 /usr/home/wwwroot/mc-skin-server/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#21 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#22 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Console/Application.php(185): Illuminate\\Console\\Application->run()
#23 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\\Console\\Application->call()
#24 /usr/home/wwwroot/mc-skin-server/app/Http/Controllers/SetupController.php(116): Illuminate\\Foundation\\Console\\Kernel->call()
#25 [internal function]: App\\Http\\Controllers\\SetupController->finish()
#26 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#27 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#28 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#29 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#30 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#31 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#32 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/CheckInstallation.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckInstallation->handle()
#34 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/RedirectToSetup.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RedirectToSetup->handle()
#36 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/ForbiddenIE.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ForbiddenIE->handle()
#38 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#40 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#42 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#44 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#46 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#48 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#50 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#51 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#52 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#53 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#54 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#55 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/DetectLanguagePrefer.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#57 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /usr/home/wwwroot/mc-skin-server/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#60 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#62 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#64 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#66 /usr/home/wwwroot/mc-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#67 /usr/home/wwwroot/mc-skin-server/public/index.php(48): Illuminate\\Foundation\\Http\\Kernel->handle()
#68 {main}
"}`

原始默认报错截图
<img width="973" alt="setup-err1" src="https://user-images.githubusercontent.com/20571903/73619922-7c0e2180-466a-11ea-9679-cbd2f6723562.png">

按提示修改 STDIN 为 ‘STDIN’ 后的报错截图
<img width="973" alt="setup-err2" src="https://user-images.githubusercontent.com/20571903/73619983-ca232500-466a-11ea-8d59-425b0bc75291.png">

## Steps to Reproduce 重现步骤
正常标准的安装步骤
下载zip，解压
配置nginx.conf
创建mysql数据库
浏览器访问执行 setup 过程

**Comment by m00nfly** [comment]
我重新 clone 最新 reace 分支的代码，手动编译构建后成功安装；
所以这应该是一个已经解决的bug，等待release 合并就OK了！
感谢开发者，所以这个 issue 就关闭了吧！
