### ISSUE TITLE
Blank page during setup

### ISSUE THREAD

**Issue by poopingpenis** [bs-community/blessing-skin-server#167]
I'm trying to install Blessing Skin on my raspi, and have nginx and mariadb setup for it, but as soon as I visit the setup page (or even the root page) it's all just blank.

Here's my nginx configuration:

```
server {
        listen 80;
        root /var/www/skins.loc/public;
        index index.php index.html index.htm index.nginx-debian.html;
        server_name skins.loc;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        }

        location ~ /\.ht {
                deny all;
        }

        location ~ /\.env {
                deny all;
        }
}
```

I don't really have an error codes or messages to show, unfortunately.

I also haven't setup a mail server, is one necessary?

**Comment by g-plane** [comment]
Mail server isn't necessary. Can you find the log located at `storage/logs`? If so, please upload to pastebin and give us the link.

**Comment by g-plane** [comment]
Also, don't forget to turn on the debug mode by setting `APP_DEBUG=true` in `.env` file.

**Comment by poopingpenis** [comment]
I ran cat on laravel-2020-04-28.log (the only log file present) and got these sample errors:

```
[previous exception] [object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blessingskin.language_lines' doesn't exist (SQL: select * from `language_lines` where `group` = *)\"). at /var/www/skins.loc/resources/views/errors/500.twig:7)
[stacktrace]


[previous exception] [object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blessingskin.language_lines' doesn't exist (SQL: select * from `language_lines` where `group` = *) at /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blessingskin.language_lines' doesn't exist at /var/www/skins.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63)
[stacktrace]

#48 {main}
"}
[2020-04-28 11:09:52] production.ERROR: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blessingskin.language_lines' doesn't exist in /var/www/skins.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61
Stack trace:
#0 /var/www/skins.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)
#1 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Doctrine\DBAL\Driver\PDOConnection->prepare('select * from `...')
#2 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#3 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#4 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run('select  {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blessingskin.language_lines' doesn't exist in /var/www/skins.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61
Stack trace:
#0 /var/www/skins.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)
#1 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')
#2 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#3 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#4 /var/www/skins.loc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run('select  at /var/www/skins.loc/resources/views/errors/500.twig:7)
[stacktrace]
#0 {main}
"}

```

The reason I don't have more is because I deleted the file to regenerate it after reloading nginx but it never showed up. Maybe this can be helpful though

**Comment by g-plane** [comment]
Try running this command: `php artisan migrate`. Answer "yes" if a prompt is showed.

**Comment by poopingpenis** [comment]
That worked! Thank you very much :)
