### ISSUE TITLE
PHP 8.1 导致无法访问站点

### ISSUE THREAD

**Issue by Big-Cake-jpg** [bs-community/blessing-skin-server#349]
### Which version of Blessing Skin are you using?

6.0.0-beta.4

### Which version of PHP are you using?

8.1

### What browsers are you seeing the problem on?

Microsoft Edge

### Which web server are you using?

Apache

### What happened?

在 PHP 8.1 环境下，已经解除了所有函数的禁用，但是站点无法访问
（我在使用宝塔面板）
原本在 PHP 8.0 / 7.x 下，站点正常运转，但是更换为 PHP 8.1 即可出现问题

> 更换之前：
> ![image](https://user-images.githubusercontent.com/76810494/143679403-ac968d20-6b9a-42f0-9942-28741eea2c87.png)
> 更换之后：
> ![image](https://user-images.githubusercontent.com/76810494/143679456-e85485c5-9f58-47be-9278-3c1b38b043ec.png)

宝塔面板的函数禁用列表如下：
![image](https://user-images.githubusercontent.com/76810494/143679514-706f4e8d-9c65-4c4a-be1b-1940b73271f4.png)

中文模版没法提交 Issue 就离谱 ~sb GitHub~

### Error Logs

```text
[2021-11-27 19:34:55] production.ERROR: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Collections\Collection.php:1443
Stack trace:
#0 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(13): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', 'C:\\wwwroot\\skin...', 1443)
#1 C:\wwwroot\skin.cakemc.top\vendor\composer\ClassLoader.php(571): include('C:\\wwwroot\\skin...')
#2 C:\wwwroot\skin.cakemc.top\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\wwwroot\\skin...')
#3 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Collections\helpers.php(15): Composer\Autoload\ClassLoader->loadClass('Illuminate\\Supp...')
#4 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(89): collect(Array)
#5 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config('aliases')
#6 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(237): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap(Object(Illuminate\Foundation\Application))
#8 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(152): Illuminate\Foundation\Application->bootstrapWith(Array)
#9 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(136): Illuminate\Foundation\Http\Kernel->bootstrap()
#10 C:\wwwroot\skin.cakemc.top\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#11 C:\wwwroot\skin.cakemc.top\public\index.php(61): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#12 {main} {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\\Support\\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php:1443
Stack trace:
#0 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(13): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Return type of ...', 'C:\\\\wwwroot\\\\skin...', 1443)
#1 C:\\wwwroot\\skin.cakemc.top\\vendor\\composer\\ClassLoader.php(571): include('C:\\\\wwwroot\\\\skin...')
#2 C:\\wwwroot\\skin.cakemc.top\\vendor\\composer\\ClassLoader.php(428): Composer\\Autoload\\includeFile('C:\\\\wwwroot\\\\skin...')
#3 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\helpers.php(15): Composer\\Autoload\\ClassLoader->loadClass('Illuminate\\\\Supp...')
#4 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\PackageManifest.php(89): collect(Array)
#5 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\PackageManifest.php(78): Illuminate\\Foundation\\PackageManifest->config('aliases')
#6 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
#7 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap(Object(Illuminate\\Foundation\\Application))
#8 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#9 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#10 C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#11 C:\\wwwroot\\skin.cakemc.top\\public\\index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#12 {main} at C:\\wwwroot\\skin.cakemc.top\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php:13)
[stacktrace]
#0 {main}
"}
```

### Steps to Reproduce

1. 更改 PHP 版本
2. 访问站点 [skin.cakemc.top](https://skin.cakemc.top)

**Comment by Big-Cake-jpg** [comment]
有人没（

**Comment by ilworkcn** [comment]
系统还是用linux吧 windows下跑blessingskin真的玄学

**Comment by XieXiLin158** [comment]
不是系统问题，Pig Fang说他没搞composer



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 晚上6:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [bs-community/blessing-skin-server] PHP 8.1 导致无法访问站点 (Issue #349)





 
系统还是用linux吧 windows下跑blessingskin真的玄学
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mochaaP** [comment]
closing as <https://github.com/bs-community/blessing-skin-server/commit/88b5da401a963daea10e4c55e2853810757fb090>

**Comment by g-plane** [comment]
[6.0.0-rc.1](https://github.com/bs-community/blessing-skin-server/releases/tag/6.0.0-rc.1) 已发布，支持 PHP 8.1。
