### ISSUE TITLE
邮件无法正常发送

### ISSUE THREAD

**Issue by vlssu** [bs-community/blessing-skin-server#352]
### Blessing Skin 版本

2021年12 月14 日提交11a2c602eee727c5fa8be997445d99e527b1302e

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [x] 是

### 出现了什么问题？

![image](https://user-images.githubusercontent.com/43847794/147306310-385d161d-0256-4bb7-a4de-22c8effa9b17.png)

使用最新的（2021年12 月14 日提交11a2c602eee727c5fa8be997445d99e527b1302e）编译出来的开发版，出现无法正常发送邮件的问题

我将beta4编译的开发版再次覆盖最新版的不仅修复了语言策略错误也修复了邮件发送失败的问题

### 错误日志

```text
[2021-12-22 00:45:33] production.ERROR: Method Illuminate\Support\Stringable::when does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Support\\Stringable::when does not exist. at /bsskin/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]
#0 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php(148): Illuminate\\Support\\Stringable->__call()
#1 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php(77): Illuminate\\View\\Compilers\\BladeCompiler->wrapInEchoHandler()
#2 [internal function]: Illuminate\\View\\Compilers\\BladeCompiler->Illuminate\\View\\Compilers\\Concerns\\{closure}()
#3 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php(80): preg_replace_callback()
#4 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php(42): Illuminate\\View\\Compilers\\BladeCompiler->compileRawEchos()
#5 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(397): Illuminate\\View\\Compilers\\BladeCompiler->compileEchos()
#6 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(246): Illuminate\\View\\Compilers\\BladeCompiler->parseToken()
#7 /bsskin/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(154): Illuminate\\View\\Compilers\\BladeCompiler->compileString()
#8 /bsskin/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(55): Illuminate\\View\\Compilers\\BladeCompiler->compile()
#9 /bsskin/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#10 /bsskin/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#11 /bsskin/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#12 /bsskin/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#13 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(382): Illuminate\\View\\View->render()
#14 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(355): Illuminate\\Mail\\Mailer->renderView()
#15 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(273): Illuminate\\Mail\\Mailer->addContent()
#16 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(187): Illuminate\\Mail\\Mailer->send()
#17 /bsskin/plugins/oauth-github/vendor/illuminate/support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#18 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(188): Illuminate\\Mail\\Mailable->withLocale()
#19 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(304): Illuminate\\Mail\\Mailable->send()
#20 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(258): Illuminate\\Mail\\Mailer->sendMailable()
#21 /bsskin/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(124): Illuminate\\Mail\\Mailer->send()
#22 /bsskin/app/Http/Controllers/UserController.php(163): Illuminate\\Mail\\PendingMail->send()
#23 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\UserController->sendVerificationEmail()
#24 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#25 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#26 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#27 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#28 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#29 /bsskin/plugins/single-player-limit/src/RequireBindPlayer.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): SinglePlayerLimit\\RequireBindPlayer->handle()
#31 /bsskin/app/Http/Middleware/FireUserAuthenticated.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\FireUserAuthenticated->handle()
#33 /bsskin/app/Http/Middleware/EnsureEmailFilled.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureEmailFilled->handle()
#35 /bsskin/app/Http/Middleware/RejectBannedUser.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RejectBannedUser->handle()
#37 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#39 /bsskin/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#41 /bsskin/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#43 /bsskin/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#45 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#47 /bsskin/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#49 /bsskin/plugins/oauth-github/vendor/illuminate/session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /bsskin/plugins/oauth-github/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#51 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#52 /bsskin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#54 /bsskin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#56 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#58 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#59 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#60 /bsskin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#61 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#62 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#63 /bsskin/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#65 /bsskin/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#67 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#69 /bsskin/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#70 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#71 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#73 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#74 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#76 /bsskin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#78 /bsskin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#79 /bsskin/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#80 {main}
"} 
```

### 重现步骤

使用最新的（2021年12 月14 日提交11a2c602eee727c5fa8be997445d99e527b1302e）编译出来的开发版
覆盖前一个版本（beta4开发版）即可出现问题

**Comment by 9965086** [comment]
邮箱哪里配置啊 没找到入口=.=

**Comment by XieXiLin158** [comment]
.env文件里进行配置.
详细请看Docs




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月13日(星期四) 中午11:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352)





 
邮箱哪里配置啊 没找到入口=.=
 
&mdash;

**Comment by 9965086** [comment]
> .env文件里进行配置. 详细请看Docs
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月13日(星期四) 中午11:52 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352) 邮箱哪里配置啊 没找到入口=.= &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢

**Comment by 9965086** [comment]
> 

https://blessing.netlify.app/en/setup.html#environment-requirements
在里面没有看到.env详解=.=
请大佬指点

**Comment by 9965086** [comment]
> 

![image](https://user-images.githubusercontent.com/85790323/149265468-e2b322f1-fe08-46c8-af25-ea3d2dd3d57a.png)

**Comment by 9965086** [comment]
> 

![image](https://user-images.githubusercontent.com/85790323/149265529-e942fc42-164a-40da-8016-92c368a00c97.png)
哪里不对吗

**Comment by XieXiLin158** [comment]
FROM_ADDRESS需要填写邮箱地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月13日(星期四) 中午12:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352)





   

 哪里不对吗
 
&mdash;

**Comment by 9965086** [comment]
OK了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月13日(星期四) 中午12:24
收件人: ***@***.***&gt;; 
抄送: "Guo ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352)





 FROM_ADDRESS需要填写邮箱地址 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年1月13日(星期四) 中午12:22 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352) 
 
 
 
 
 
     
 
  哪里不对吗 
   
 &amp;mdash; 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 9965086** [comment]
大佬这个位置在哪，方便告诉下吗 没找到=.=




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bs-community/blessing-skin-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 中午12:24
***@***.***&gt;;
抄送:&nbsp;"Guo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352)





 FROM_ADDRESS需要填写邮箱地址 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年1月13日(星期四) 中午12:22 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352) 
 
 
 
 
 
     
 
  哪里不对吗 
   
 &amp;mdash; 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XieXiLin158** [comment]
你的网站目录下，public文件夹的上一级文件夹




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月13日(星期四) 中午1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352)





 大佬这个位置在哪，方便告诉下吗 没找到=.= 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        &quot;bs-community/blessing-skin-server&quot;                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年1月13日(星期四) 中午12:24 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;&quot;Guo ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352) 
 
 
 
 
 
  FROM_ADDRESS需要填写邮箱地址  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2022年1月13日(星期四) 中午12:22  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [bs-community/blessing-skin-server] 邮件无法正常发送 (Issue #352)  
   
   
   
   
   
       
   
   哪里不对吗  
     
  &amp;amp;mdash;  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
&mdash;
