### ISSUE TITLE
插件市场打开出现严重错误Undefined array key "packages"

### ISSUE THREAD

**Issue by lbs8851** [bs-community/blessing-skin-server#465]
### Which version of Blessing Skin are you using?

6.0.2

### Which version of PHP are you using?

8.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Which web server are you using?

Apache

### What happened?

打开皮肤站管理面板里的插件市场弹出
![image](https://user-images.githubusercontent.com/78454680/183320486-3d42ad6e-66f4-44d3-9789-3fdf7dc3d1b7.png)
严重错误
×
Undefined array key "packages"
详情
[1] app\Http\Controllers\MarketController.php#L91
[2] app\Http\Controllers\MarketController.php#L95
[3] app\Http\Controllers\MarketController.php#L20
[4] app\Http\Middleware\CheckRole.php#L22
[5] app\Http\Middleware\FireUserAuthenticated.php#L15
[6] app\Http\Middleware\EnsureEmailFilled.php#L17
[7] app\Http\Middleware\RejectBannedUser.php#L23
[8] app\Http\Middleware\RedirectToSetup.php#L28
[9] app\Http\Middleware\EnforceEverGreen.php#L23
[10] app\Http\Middleware\DetectLanguagePrefer.php#L30
[11] app\Http\Middleware\ConvertEmptyStringsToNull.php#L23

尝试过重装皮肤站也无法解决该问题。

### Error Logs

```text
[2022-08-08 09:09:39] production.ERROR: Undefined array key "packages" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"packages\" at D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Controllers\\MarketController.php:91)
[stacktrace]
#0 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Controllers\\MarketController.php(91): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', 'D:\\\\wwwroot\\\\skin...', 91)
#1 [internal function]: App\\Http\\Controllers\\MarketController->App\\Http\\Controllers\\{closure}('https://gplane....', 0)
#2 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(664): array_map(Object(Closure), Array, Array)
#3 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Controllers\\MarketController.php(95): Illuminate\\Support\\Collection->map(Object(Closure))
#4 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Controllers\\MarketController.php(20): App\\Http\\Controllers\\MarketController->fetch()
#5 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\MarketController->marketData(Object(App\\Services\\PluginManager))
#6 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('marketData', Array)
#7 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\MarketController), 'marketData')
#8 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#9 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Routing\\Route->run()
#10 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\CheckRole.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckRole->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')
#13 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\FireUserAuthenticated.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\FireUserAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\EnsureEmailFilled.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\EnsureEmailFilled->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\RejectBannedUser.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\RejectBannedUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'web')
#23 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#33 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 D:\\wwwroot\\skin.mixfish.games\\app\\Http\\Middleware\\ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 D:\\wwwroot\\skin.mixfish.games\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#59 D:\\wwwroot\\skin.mixfish.games\\public\\index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#60 {main}
"}
```

### Steps to Reproduce

打开插件市场后弹出严重错误

**Comment by Big-Cake-jpg** [comment]
https://t.me/blessing_skin_news/781

请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上

**Comment by MuYouYuanNing** [comment]
> https://t.me/blessing_skin_news/781
> 
> 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上

是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了

**Comment by Big-Cake-jpg** [comment]
> > https://t.me/blessing_skin_news/781
> 
> > 
> 
> > 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上
> 
> 
> 
> 是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了

PLUGIN_REGISTRY=xxxxxx

**Comment by songhao2009** [comment]
> > > https://t.me/blessing_skin_news/781
> > 
> > 
> > > 
> > 
> > 
> > > 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上
> > 
> > 
> > 是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了
> 
> PLUGIN_REGISTRY=xxxxxx

在哪改？

**Comment by Big-Cake-jpg** [comment]
> > > > https://t.me/blessing_skin_news/781
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上
> 
> > > 
> 
> > > 
> 
> > > 是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了
> 
> > 
> 
> > PLUGIN_REGISTRY=xxxxxx
> 
> 
> 
> 在哪改？

.env

**Comment by songhao2009** [comment]
> > > > > https://t.me/blessing_skin_news/781
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了
> > 
> > 
> > > 
> > 
> > 
> > > PLUGIN_REGISTRY=xxxxxx
> > 
> > 
> > 在哪改？
> 
> .env

PLUGIN_REGISTRY=xxxxxx中
xxxxxx该填什么

**Comment by Big-Cake-jpg** [comment]
@songhao2009 啊啊啊啊啊啊，你看看上面的链接不行吗

**Comment by XieXiLin3** [comment]
> > > > > > https://t.me/blessing_skin_news/781
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > PLUGIN_REGISTRY=xxxxxx
> > > 
> > > 
> > > 在哪改？
> > 
> > 
> > .env
> 
> PLUGIN_REGISTRY=xxxxxx中 xxxxxx该填什么

……我想说呢，麻烦您看一下频道通知。

指定：
PLUGINS_REGISTRY=https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_{lang}.json
（無須替換 {lang}。）

**Comment by Broken-Deer** [comment]
![image](https://user-images.githubusercontent.com/64290747/185610397-84ac6457-0532-4c8f-a748-a7c528c03fd0.png)
更换插件源后出现问题

**Comment by mochaaP** [comment]
@kxsclu 自查網路問題

**Comment by Broken-Deer** [comment]
> @kxsclu 自查網路問題

浏览器直接访问https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_cn.json显示“Retry later”，“https://git.qvq.network/”也是一样

**Comment by Broken-Deer** [comment]
哦现在好了

**Comment by Broken-Deer** [comment]
那个网站似乎会经常罢工

**Comment by Purple-City** [comment]
> > > > > > https://t.me/blessing_skin_news/781
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > 请在更换插件源前确保使用的 OpenSSL 版本为 1.1.1 以上
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 是啥意思捏？最近发现好几个皮肤站都这样，我的也这样，突然间出现的，插件源找不到在哪换，之前还好好的，啥也没动就这样了
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > PLUGIN_REGISTRY=三十
> > > 
> > > 
> > > 在哪改？
> > 
> > 
> > .env
> 
> PLUGIN_REGISTRY=xxxxxx中 xxxxxx该填什么

兄弟我也打不开插件市场，可以把yggdrasil api插件的压缩包发给我吗，我手动上传

**Comment by Purple-City** [comment]
> 那个网站似乎会经常罢工

兄弟我也打不开插件市场，可以把yggdrasil api插件的压缩包发给我吗，我手动上传

**Comment by Big-Cake-jpg** [comment]
@Purple-City https://github.com/bs-community/plugins-dist

**Comment by Purple-City** [comment]
> @Purple城市 https://github.com/bs-community/plugins-dist

谢谢

**Comment by Purple-City** [comment]
> @Purple城市 https://github.com/bs-community/plugins-dist

<img width="1280" alt="屏幕截图 2022-10-10 141208" src="https://user-images.githubusercontent.com/115448049/194807209-dfc4e2de-f563-4ce1-8805-76d75271fc11.png">
我点击"yggdrasil-api_5.1.5.zip"出现这个，可以告诉我怎么下载吗，我不是很了解GitHub
