### ISSUE TITLE
 OAuth 客户端核心插件没法正常使用

### ISSUE THREAD

**Issue by xiaojiang233** [bs-community/blessing-skin-server#498]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

 OAuth 客户端核心插件没法正常使用，提示存在错误
Littleskin和live登录插件也没法正常使用（已配置）

### 错误日志

```text
[2022-11-14 11:36:43] production.ERROR: Class "Laravel\Socialite\Facades\Socialite" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"Laravel\\Socialite\\Facades\\Socialite\" not found at /www/wwwroot/skin.xiaojiang233.xyz/plugins/mojang-verification/src/AccountController.php:25)
[stacktrace]
#0 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): GPlane\\Mojang\\AccountController->verify()
#1 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#2 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#3 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#4 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#5 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#6 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#8 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#10 /www/wwwroot/skin.xiaojiang233.xyz/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#12 /www/wwwroot/skin.xiaojiang233.xyz/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#14 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#16 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#18 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#20 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#21 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#23 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#25 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#27 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#29 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#31 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /www/wwwroot/skin.xiaojiang233.xyz/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#34 /www/wwwroot/skin.xiaojiang233.xyz/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#36 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /www/wwwroot/skin.xiaojiang233.xyz/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#39 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#40 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#43 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#47 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#48 /www/wwwroot/skin.xiaojiang233.xyz/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#49 {main}
"} 
[2022-11-14 11:37:28] production.ERROR: Class "SocialiteProviders\Manager\ServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"SocialiteProviders\\Manager\\ServiceProvider\" not found at /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745)
[stacktrace]
#0 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(679): Illuminate\\Foundation\\Application->resolveProvider()
#1 /www/wwwroot/skin.xiaojiang233.xyz/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
#2 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
#3 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
#8 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
#9 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
#10 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): App\\Services\\PluginManager->App\\Services\\{closure}()
#11 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
#12 /www/wwwroot/skin.xiaojiang233.xyz/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
#13 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
#14 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#18 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#19 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#21 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#22 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#24 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#25 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#26 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#27 /www/wwwroot/skin.xiaojiang233.xyz/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#28 {main}
"} 
[2022-11-14 11:37:29] production.ERROR: Class "SocialiteProviders\Manager\ServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"SocialiteProviders\\Manager\\ServiceProvider\" not found at /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745)
[stacktrace]
#0 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(679): Illuminate\\Foundation\\Application->resolveProvider()
#1 /www/wwwroot/skin.xiaojiang233.xyz/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
#2 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
#3 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
#8 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
#9 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
#10 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): App\\Services\\PluginManager->App\\Services\\{closure}()
#11 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
#12 /www/wwwroot/skin.xiaojiang233.xyz/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
#13 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
#14 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#18 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#19 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#21 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#22 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#24 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#25 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#26 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#27 /www/wwwroot/skin.xiaojiang233.xyz/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#28 {main}
"} 
[2022-11-14 11:37:29] production.ERROR: Class "SocialiteProviders\Manager\ServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"SocialiteProviders\\Manager\\ServiceProvider\" not found at /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745)
[stacktrace]
#0 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(679): Illuminate\\Foundation\\Application->resolveProvider()
#1 /www/wwwroot/skin.xiaojiang233.xyz/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
#2 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
#3 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
#8 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
#9 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
#10 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): App\\Services\\PluginManager->App\\Services\\{closure}()
#11 /www/wwwroot/skin.xiaojiang233.xyz/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
#12 /www/wwwroot/skin.xiaojiang233.xyz/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
#13 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
#14 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#18 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#19 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#21 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#22 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#24 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#25 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#26 /www/wwwroot/skin.xiaojiang233.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#27 /www/wwwroot/skin.xiaojiang233.xyz/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#28 {main}
"}
```

### 重现步骤

开启OAuth 客户端核心插件，然后再刷新就提示出错。

**Comment by xiaojiang233** [comment]
换了Nginx还是一样...

**Comment by Linecom233** [comment]
从插件市场安装就不会报错

**Comment by Pimeng** [comment]
现在还有谁能打开插件市场吗...

**Comment by gxres042** [comment]
> 现在还有谁能打开插件市场吗...

麻烦同学看一下置顶 Issue 哈
