### ISSUE TITLE
http 500

### ISSUE THREAD

**Issue by xiaoLangZe** [bs-community/blessing-skin-server#526]
### Blessing Skin 版本

blessing-skin-server-6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

nginx 报错500
我把public/index.php内部修改成<?php phpinfo(); ?>可以运行

### 错误日志

```text
2023/01/14 15:35:17 [error] 5328#12176: *55 FastCGI sent in stderr: "PHP Fatal error:  Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php on line 98 and defined in C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php:928
Stack trace:
#0 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php(98): Carbon\Carbon::setLastErrors(false)
#1 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php(252): Carbon\Carbon->__construct(NULL, NULL)
#2 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Support\InteractsWithTime.php(37): Carbon\Carbon::now()
#3 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\FileStore.php(317): Illuminate\Cache\FileStore->availableAt(0)
#4 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\FileStore.php(77): Illuminate\Cache\FileStore->expiration(0)
#5 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\FileStore.php(200): Illuminate\Cache\FileStore->put('yaml-trans-8357...', Array, 0)
#6 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(363): Illuminate\Cache\FileStore->forever('yaml-trans-8357...', Array)
#7 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(204): Illuminate\Cache\Repository->forever('yaml-trans-8357...', Array)
#8 C:\Users\xshao\Desktop\webkit\nginx\html\skin\app\Services\Translations\Yaml.php(27): Illuminate\Cache\Repository->put('yaml-trans-8357...', Array)
#9 C:\Users\xshao\Desktop\webkit\nginx\html\skin\app\Services\Translations\Loader.php(16): App\Services\Translations\Yaml->parse('C:\\Users\\xshao\\...')
#10 C:\
2023/01/14 15:35:17 [error] 5328#12176: *55 FastCGI sent in stderr: "y)
#21 C:\Users\xshao\Desktop\webkit\nginx\html\skin\storage\framework\views\twig\d2\d2f41c0d83bc40060cfe269e898310e66840ea6919367947fe1c1477454023ad.php(43): TwigBridge\Twig\Template->display(Array, Array)
#22 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\twig\twig\src\Template.php(405): __TwigTemplate_75da13b6039544b2f35a5c87bc6b3f13a469bea9c12e9ee0cbea6dbd4d0e7767->doDisplay(Array, Array)
#23 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\twig\twig\src\Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\rcrowe\twigbridge\src\Twig\Template.php(41): Twig\Template->display(Array, Array)
#25 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\twig\twig\src\Template.php(390): TwigBridge\Twig\Template->display(Array)
#26 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\rcrowe\twigbridge\src\Engine\Twig.php(92): Twig\Template->render(Array)
#27 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\View\View.php(139): TwigBridge\Engine\Twig->get('C:\\Users\\xshao\\...', Array)
#28 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
#29 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#30 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#31 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#32 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(55): Illuminate\Http\Response->__construct(Object(Illuminate\View\View), 500, Array)
#33 C:\Users\xshao\Desktop\webkit\nginx\h
2023/01/14 15:35:17 [error] 5328#12176: *55 FastCGI sent in stderr: "n\Traits\Creator.php:928
Stack trace:
#0 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php(98): Carbon\Carbon::setLastErrors(false)
#1 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php(252): Carbon\Carbon->__construct(NULL, NULL)
#2 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Support\InteractsWithTime.php(37): Carbon\Carbon::now()
#3 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\FileStore.php(317): Illuminate\Cache\FileStore->availableAt(0)
#4 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\FileStore.php(77): Illuminate\Cache\FileStore->expiration(0)
#5 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\FileStore.php(200): Illuminate\Cache\FileStore->put('yaml-trans-8357...', Array, 0)
#6 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(363): Illuminate\Cache\FileStore->forever('yaml-trans-8357...', Array)
#7 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(204): Illuminate\Cache\Repository->forever('yaml-trans-8357...', Array)
#8 C:\Users\xshao\Desktop\webkit\nginx\html\skin\app\Services\Translations\Yaml.php(27): Illuminate\Cache\Repository->put('yaml-trans-8357...', Array)
#9 C:\Users\xshao\Desktop\webkit\nginx\html\skin\app\Services\Translations\Loader.php(16): App\Services\Translations\Yaml->parse('C:\\Users\\xshao\\...')
#10 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php(67): App\Services\Translations\Loader->loadPath('C:\\Users\\xshao\\...', 'zh_CN', 'errors')
#11 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\spatie\laravel-translation-loader\src\TranslationLoaderManager.php(21): Illuminat
2023/01/14 15:35:17 [error] 5328#12176: *55 FastCGI sent in stderr: "3f13a469bea9c12e9ee0cbea6dbd4d0e7767->doDisplay(Array, Array)
#23 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\twig\twig\src\Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\rcrowe\twigbridge\src\Twig\Template.php(41): Twig\Template->display(Array, Array)
#25 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\twig\twig\src\Template.php(390): TwigBridge\Twig\Template->display(Array)
#26 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\rcrowe\twigbridge\src\Engine\Twig.php(92): Twig\Template->render(Array)
#27 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\View\View.php(139): TwigBridge\Engine\Twig->get('C:\\Users\\xshao\\...', Array)
#28 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
#29 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#30 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#31 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#32 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(55): Illuminate\Http\Response->__construct(Object(Illuminate\View\View), 500, Array)
#33 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(85): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#34 C:\Users\xshao\Desktop\webkit\nginx\html\skin\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(582): Illuminate\Routing\ResponseFactory->view('err
```

### 重现步骤

启动nginx和php？

**Comment by xiaoLangZe** [comment]
抱歉我用的是php8.2，使用8.1没有问题

**Comment by TennousuAthena** [comment]
PHP 8.2 可能会出现此问题
尝试在开发环境下
```composer update nesbot/carbon```

**Comment by g-plane** [comment]
我们已经更新了依赖，现在应该支持 PHP 8.2。
