### ISSUE TITLE
正版验证插件无法验证，azure已经配置了

### ISSUE THREAD

**Issue by SRY-CTB** [bs-community/blessing-skin-server#531]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

正版验证插件无法验证，azure已经配置了，但返回“我们无法完成你的请求
unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.”

### 错误日志

```text
[2023-01-22 14:40:40] production.ERROR: cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json {"userId":1,"exception":"[object] (Illuminate\\Http\\Client\\ConnectionException(code: 0): cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json at /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php:680)
[stacktrace]
#0 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Support/helpers.php(234): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#1 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(682): retry()
#2 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(537): Illuminate\\Http\\Client\\PendingRequest->send()
#3 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Controllers/MarketController.php(88): Illuminate\\Http\\Client\\PendingRequest->get()
#4 [internal function]: App\\Http\\Controllers\\MarketController->App\\Http\\Controllers\\{closure}()
#5 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(664): array_map()
#6 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Controllers/MarketController.php(95): Illuminate\\Support\\Collection->map()
#7 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Controllers/MarketController.php(20): App\\Http\\Controllers\\MarketController->fetch()
#8 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\MarketController->marketData()
#9 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#10 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#11 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#12 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#13 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/CheckRole.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckRole->handle()
#16 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/FireUserAuthenticated.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\FireUserAuthenticated->handle()
#18 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/EnsureEmailFilled.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureEmailFilled->handle()
#20 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/RejectBannedUser.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RejectBannedUser->handle()
#22 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#24 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#26 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#28 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#30 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#32 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#43 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#45 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#47 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /www/wwwroot/star-skin.shanrenyi.top/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#50 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#52 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#55 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#56 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#58 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#59 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#61 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#63 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#64 /www/wwwroot/star-skin.shanrenyi.top/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#65 {main}

[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json at /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
[stacktrace]
#0 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(870): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(840): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#7 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(826): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#8 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#9 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Middleware.php(37): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#10 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#11 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\\RedirectMiddleware->__invoke()
#12 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#13 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke()
#14 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#15 /www/wwwroot/star-skin.shanrenyi.top/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#16 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(737): GuzzleHttp\\Client->request()
#17 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(668): Illuminate\\Http\\Client\\PendingRequest->sendRequest()
#18 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Support/helpers.php(234): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#19 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(682): retry()
#20 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/http/Client/PendingRequest.php(537): Illuminate\\Http\\Client\\PendingRequest->send()
#21 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Controllers/MarketController.php(88): Illuminate\\Http\\Client\\PendingRequest->get()
#22 [internal function]: App\\Http\\Controllers\\MarketController->App\\Http\\Controllers\\{closure}()
#23 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(664): array_map()
#24 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Controllers/MarketController.php(95): Illuminate\\Support\\Collection->map()
#25 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Controllers/MarketController.php(20): App\\Http\\Controllers\\MarketController->fetch()
#26 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\MarketController->marketData()
#27 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#28 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#29 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#30 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#31 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#32 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/CheckRole.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckRole->handle()
#34 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/FireUserAuthenticated.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\FireUserAuthenticated->handle()
#36 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/EnsureEmailFilled.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureEmailFilled->handle()
#38 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/RejectBannedUser.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RejectBannedUser->handle()
#40 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#42 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#44 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#46 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#48 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#50 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#52 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /www/wwwroot/star-skin.shanrenyi.top/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#54 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#55 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#57 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#59 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#61 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#62 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#63 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#64 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#65 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#66 /www/wwwroot/star-skin.shanrenyi.top/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#68 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#70 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#72 /www/wwwroot/star-skin.shanrenyi.top/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#73 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#74 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#76 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#77 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#79 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#81 /www/wwwroot/star-skin.shanrenyi.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#82 /www/wwwroot/star-skin.shanrenyi.top/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#83 {main}
"}
```

### 重现步骤

下载插件。配置。env。使用插件。

**Comment by Linecom-lik** [comment]
创建azure应用的时候权限选错了，应该是带个人Microsoft账户的：
![image](https://user-images.githubusercontent.com/69106177/216032470-7ef7d640-7ddc-45dc-b5e8-219cf63fe793.png)

**Comment by Andowa** [comment]
> 创建azure应用的时候权限选错了，应该是带个人Microsoft账户的： ![image](https://user-images.githubusercontent.com/69106177/216032470-7ef7d640-7ddc-45dc-b5e8-219cf63fe793.png)

请教下，MICROSOFT_SECRET的值是在哪里查看？

**Comment by Linecom-lik** [comment]
> > 创建azure应用的时候权限选错了，应该是带个人Microsoft账户的： ![image](https://user-images.githubusercontent.com/69106177/216032470-7ef7d640-7ddc-45dc-b5e8-219cf63fe793.png)
> 
> 请教下，MICROSOFT_SECRET的值是在哪里查看？

只会在创建密钥的时候显示，刷新或者关掉就不能显示了
