### ISSUE TITLE
安装过程执行php artisan key:generate命令时报错

### ISSUE THREAD

**Issue by CleMooling** [bs-community/blessing-skin-server#551]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

php版本使用的8.2.4！（选项只提供到8.1，特此说明）
按照wiki安装教程，在生成app key这一步执行php artisan key:generate时产生大量报错（粗略搜索发现网上没有相关报错的信息）且key没有被生成。
在nginx配置无误后（自我感觉没有问题），进入localhost/setup时出现500 Internal Server Error错误，且没有与blessing-skin相关的字样出现，storage没有输出日志（有过一次，但是后面删除掉再次重试发现始终不会生成）。
下面是生成app key时的报错内容（截图）：
![Screenshot_20230406_231447](https://user-images.githubusercontent.com/93636342/230423380-7dd45528-ae7a-4b8d-876d-32a198788125.png)
![Screenshot_20230406_231529](https://user-images.githubusercontent.com/93636342/230423457-bf8e0c2c-0e78-4e3c-852c-eab5d47c8ffc.png)
![Screenshot_20230406_231558](https://user-images.githubusercontent.com/93636342/230423512-8b826977-7494-4d2d-ae01-21deae72e679.png)

### 错误日志

```text
php artisan key:generate

   TypeError 

  Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /home/mooling/Services/blessing-skin-server/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98

  at vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928
    924▕      * @param array $lastErrors
    925▕      *
    926▕      * @return void
    927▕      */
  ➜ 928▕     private static function setLastErrors(array $lastErrors)
    929▕     {
    930▕         static::$lastErrors = $lastErrors;
    931▕     }
    932▕ 

   Whoops\Exception\ErrorException 

  Using ${var} in strings is deprecated, use {$var} instead

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕ 
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕ 
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
#1 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(571): include()
#2 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(345): Illuminate\Support\Arr::where()
#8 /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /home/mooling/Services/blessing-skin-server/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle()
#14 [internal function]: Whoops\Run->handleException()
#15 {main}
  thrown in /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52

   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
#1 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(571): include()
#2 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(345): Illuminate\Support\Arr::where()
#8 /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /home/mooling/Services/blessing-skin-server/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle()
#14 [internal function]: Whoops\Run->handleException()
#15 {main}
  thrown

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕ 
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕ 
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
#1 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(571): include()
#2 /home/mooling/Services/blessing-skin-server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(345): Illuminate\Support\Arr::where()
#8 /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /home/mooling/Services/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(72): NunoMaduro\Collision\Handler->handle()
#14 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(178): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole()
#15 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(164): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#16 /home/mooling/Services/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(200): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#17 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#18 {main}
  thrown in /home/mooling/Services/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52
```

### 重现步骤

在Blessing Skin的安装目录下执行php artisan key:generate，显示上述报错。
配置完nginx，尝试启动nginx：sudo nginx
进入localhost，nginx显示正常工作
进入localhost/setup，显示500 Internal Server Error
打开安装目录下的storage文件夹，没有发现报错生成

**Comment by CleMooling** [comment]
其他信息
Linux发行版：Arch Linux x86_64
内核：6.2.9-x64v1-xanmod1-1
php是通过系统包管理器安装的最新版

**Comment by CleMooling** [comment]
“如果有，请编辑 .env 文件，将 APP_DEBUG 这一项的值改为 true，保存退出后再次打开皮肤站就能看到更详细的调试信息，读一读页面最顶上的报错应该就知道是什么问题了。”
该方法已尝试，没有获取到任何输出。

**Comment by CleMooling** [comment]
降低php版本后key成功生成

**Comment by CleMooling** [comment]
降低php版本后key成功生成
