### ISSUE TITLE
上传皮肤时页面为空白

### ISSUE THREAD

**Issue by PonderFox0643** [bs-community/blessing-skin-server#553]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

当点击“上传材质”超过两次或在这个页面刷新时就会出现空白问题

### 错误日志

```text
服务端没有错误日志，\storage\logs是空的
以下是浏览器发现的问题
app.672e119.js:2  Error: Function called outside component initialization
    at m (UploadEditor.js?v=1.3.2:1:611)
    at o (UploadEditor.js?v=1.3.2:1:2802)
    at r (UploadEditor.js?v=1.3.2:1:68)
    at Array.map (<anonymous>)
    at UploadEditor.js?v=1.3.2:1:3927
    at w (UploadEditor.js?v=1.3.2:1:1148)
    at maxLength (UploadEditor.js?v=1.3.2:1:4063)
    at new j (UploadEditor.js?v=1.3.2:1:4071)
    at UploadEditor.js?v=1.3.2:1:4359
    at app.672e119.js:2:378084
al @ app.672e119.js:2
n.callback @ app.672e119.js:2
po @ app.672e119.js:2
pl @ app.672e119.js:2
js @ app.672e119.js:2
t.unstable_runWithPriority @ app.672e119.js:2
Ui @ app.672e119.js:2
Ns @ app.672e119.js:2
ms @ app.672e119.js:2
(匿名) @ app.672e119.js:2
t.unstable_runWithPriority @ app.672e119.js:2
Ui @ app.672e119.js:2
Vi @ app.672e119.js:2
Wi @ app.672e119.js:2
Ls @ app.672e119.js:2
t.unstable_runWithPriority @ app.672e119.js:2
Ui @ app.672e119.js:2
Ds @ app.672e119.js:2
(匿名) @ app.672e119.js:2
R @ app.672e119.js:2
_.port1.onmessage @ app.672e119.js:2
app.672e119.js:2  Uncaught Error: Function called outside component initialization
    at m (UploadEditor.js?v=1.3.2:1:611)
    at o (UploadEditor.js?v=1.3.2:1:2802)
    at r (UploadEditor.js?v=1.3.2:1:68)
    at Array.map (<anonymous>)
    at UploadEditor.js?v=1.3.2:1:3927
    at w (UploadEditor.js?v=1.3.2:1:1148)
    at maxLength (UploadEditor.js?v=1.3.2:1:4063)
    at new j (UploadEditor.js?v=1.3.2:1:4071)
    at UploadEditor.js?v=1.3.2:1:4359
    at app.672e119.js:2:378084
```

### 重现步骤

web服务器使用cdn转发运行的（浏览器->域名->cdn->源站web服务器）
任意用户登录
点击上传新皮肤两次就会触发这个问题
Shift+F5强制刷新没用
重新登录也不行，其他玩家一样发生这个问题
貌似重启web服务器可能管用（这不是长期办法罢）

**Comment by SRY-CTB** [comment]
建议：检查是否使用资源描述插件，取消使用，在刷新是否上传可用

**Comment by hissincn** [comment]
Worked！

**Comment by kldhsh123** [comment]
我通过删除资源描述插件解决了问题
