### ISSUE TITLE
OAuth与最新开发版不兼容

### ISSUE THREAD

**Issue by LittleChest** [bs-community/blessing-skin-server#564]
### Blessing Skin 版本

https://github.com/bs-community/blessing-skin-server/commit/46cccdb708aa141ecce7ca34967da7b79140ad91

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

在最新开发版中安装OAuth后刷新就会出现这个
![image](https://github.com/bs-community/blessing-skin-server/assets/81231195/35e29fb8-4d87-469a-9f4b-a4812722cf77)

### 错误日志

```text
[2023-05-28 18:24:15] production.ERROR: require(/www/wwwroot/Skin/plugins/oauth/vendor/composer/../guzzlehttp/promises/src/functions_include.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): require(/www/wwwroot/Skin/plugins/oauth/vendor/composer/../guzzlehttp/promises/src/functions_include.php): Failed to open stream: No such file or directory at /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php:71)
[stacktrace]
#0 /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php(71): require()
#2 /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php(61): composerRequirea8da9aa474ea7ba9f818d455d118162d()
#3 /www/wwwroot/Skin/plugins/oauth/vendor/autoload.php(7): ComposerAutoloaderInita8da9aa474ea7ba9f818d455d118162d::getLoader()
#4 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
#5 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#6 /www/wwwroot/Skin/app/Services/PluginManager.php(160): Illuminate\\Filesystem\\Filesystem->getRequire()
#7 /www/wwwroot/Skin/app/Services/PluginManager.php(130): App\\Services\\PluginManager->loadVendor()
#8 /www/wwwroot/Skin/app/Services/PluginManager.php(116): App\\Services\\PluginManager->registerPlugin()
#9 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(245): App\\Services\\PluginManager->App\\Services\\{closure}()
#10 /www/wwwroot/Skin/app/Services/PluginManager.php(116): Illuminate\\Support\\Collection->each()
#11 /www/wwwroot/Skin/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
#12 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
#13 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#17 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#18 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#20 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#21 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#22 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#23 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#24 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#25 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#26 /www/wwwroot/Skin/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#27 {main}
"}
```

### 重现步骤

1. 下载最新预构建快照
2. 覆盖现有的Blessing Skin（或者自己建一个）
3. 去插件市场装OAuth插件
4. 刷新页面或打开任意页面

**Comment by wifi-left** [comment]
建议反馈到OAuth插件那去
还有，建议抛弃使用OAuth ~~（本人的个人恩怨）~~
