### ISSUE TITLE
PHP 8.2.8 下全新安装时出现 500 错误

### ISSUE THREAD

**Issue by DreamUniverse843** [bs-community/blessing-skin-server#574]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.2.8

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

目录权限授予后出现 500 错误，APP_DEBUG 信息如图。

![image](https://github.com/bs-community/blessing-skin-server/assets/53889721/83ec091f-8acf-4602-8a6d-41ee3a96be6f)

### 错误日志

```text
[2023-08-03 00:43:10] production.ERROR: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98 {"exception":"[object] (TypeError(code: 0): Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98 at /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928)
[stacktrace]
#0 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(98): Carbon\\Carbon::setLastErrors(false)
#1 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(252): Carbon\\Carbon->__construct(NULL, NULL)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php(37): Carbon\\Carbon::now()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/CookieJar.php(68): Illuminate\\Cookie\\CookieJar->availableAt(7200)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(315): Illuminate\\Cookie\\CookieJar->make('locale', 'zh_CN', 120, '/', NULL, NULL, true, false, 'lax')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/ResponseTrait.php(121): cookie('locale', 'zh_CN', 120)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/ResponseTrait.php(109): Illuminate\\Http\\Response->withCookie('locale', 'zh_CN', 120)
#7 /var/www/html/app/Http/Middleware/DetectLanguagePrefer.php(31): Illuminate\\Http\\Response->cookie('locale', 'zh_CN', 120)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /var/www/html/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#21 /var/www/html/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#22 {main}
"}
```

### 重现步骤

正常解压并授予目录权限。

**Comment by rainbowsource** [comment]
您好，亲爱的腐竹，这是因为，6.0.2 版本的 Blessing Skin Server 还不支持 PHP 8.2 版本，请使用 8.1。

PHP 8.1.22 官方最新线程安全版（适用于 PHP-FPM，例如 Linux 下的 Apache Module 形式）：https://windows.php.net/downloads/releases/php-8.1.22-Win32-vs16-x64.zip
PHP 8.1.22 官方最新线程不安全版（适用于 PHP FastCGI，例如 Caddy Server，Windows 下的 Nginx）：https://windows.php.net/downloads/releases/php-8.1.22-nts-Win32-vs16-x64.zip

**Comment by DreamUniverse843** [comment]
好的，感谢。
