### ISSUE TITLE
安装时无法连接到数据库提示could not find driver

### ISSUE THREAD

**Issue by happytbs** [bs-community/blessing-skin-server#576]
### Blessing Skin 版本

8.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

我在安装的过程中填写完数据库信息后点击下一步显示无法连接到数据库（账户密码正确）

### 错误日志

```text
Next Twig\\Error\\RuntimeError: An exception has been thrown during the rendering of a template (\"could not find driver (SQL: select * from `language_lines` where `group` = *)\"). in /www/sites/skin.tbstmc.xyz/index/resources/views/errors/500.twig:7
Stack trace:
#0 /www/sites/skin.tbstmc.xyz/index/storage/framework/views/twig/b5/b5f2cd38b335c0d749dfbf90d5c4a9d25af63a6af364eee9eadf631d4cc51a61.php(97): Twig\\Template->displayBlock('message', Array, Array)
#1 /www/sites/skin.tbstmc.xyz/index/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3864117e9b24fb785e0ad09eecd3de3deaa4e6a7da27048b2bfe63d64d7254fe->doDisplay(Array, Array)
#2 /www/sites/skin.tbstmc.xyz/index/vendor/twig/twig/src/Template.php(378): Twig\\Template->displayWithErrorHandling(Array, Array)
#3 /www/sites/skin.tbstmc.xyz/index/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\\Template->display(Array, Array)
#4 /www/sites/skin.tbstmc.xyz/index/storage/framework/views/twig/26/266541219d4a25e6af3008346454c9adede3c972dcca9f0b9086259caf7812ae.php(43): TwigBridge\\Twig\\Template->display(Array, Array)
#5 /www/sites/skin.tbstmc.xyz/index/vendor/twig/twig/src/Template.php(405): __TwigTemplate_72e3904ee0aa7634dab9555b3365044a98f8dd0325020f55982bcee5c3674f29->doDisplay(Array, Array)
#6 /www/sites/skin.tbstmc.xyz/index/vendor/twig/twig/src/Template.php(378): Twig\\Template->displayWithErrorHandling(Array, Array)
#7 /www/sites/skin.tbstmc.xyz/index/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\\Template->display(Array, Array)
#8 /www/sites/skin.tbstmc.xyz/index/vendor/twig/twig/src/Template.php(390): TwigBridge\\Twig\\Template->display(Array)
#9 /www/sites/skin.tbstmc.xyz/index/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): Twig\\Template->render(Array)
#10 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/View/View.php(139): TwigBridge\\Engine\\Twig->get('/www/sites/skin...', Array)
#11 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#12 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#13 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#14 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#15 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct(Object(Illuminate\\View\\View), 500, Array)
#16 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 500, Array)
#17 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(585): Illuminate\\Routing\\ResponseFactory->view('errors::500', Array, 500, Array)
#18 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#19 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#20 /www/sites/skin.tbstmc.xyz/index/app/Exceptions/Handler.php(38): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))
#21 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))
#22 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(166): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(ErrorException))
#23 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))
#24 {main}
Next ErrorException: An exception has been thrown during the rendering of a template (\"could not find driver (SQL: select * from `language_lines` where `group` = *)\"). in /www/sites/skin.tbstmc.xyz/index/resources/views/errors/500.twig:7
Stack trace:
#0 /www/sites/skin.tbstmc.xyz/index/vendor/rcrowe/twigbridge/src/Engine/Twig.php(94): TwigBridge\\Engine\\Twig->handleTwigError(Object(Twig\\Error\\RuntimeError))
#1 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/View/View.php(139): TwigBridge\\Engine\\Twig->get('/www/sites/skin...', Array)
#2 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#3 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#4 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#5 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#6 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct(Object(Illuminate\\View\\View), 500, Array)
#7 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 500, Array)
#8 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(585): Illuminate\\Routing\\ResponseFactory->view('errors::500', Array, 500, Array)
#9 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#10 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#11 /www/sites/skin.tbstmc.xyz/index/app/Exceptions/Handler.php(38): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))
#12 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))
#13 /www/sites/skin.tbstmc.xyz/index/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(166): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(ErrorException))
#14 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))
#15 {main}
  thrown at /www/sites/skin.tbstmc.xyz/index/resources/views/errors/500.twig:7)
[stacktrace]
#0 {main}
"}
```

### 重现步骤

- 打开网站
- 填写数据库信息
- 点击下一步
- 显示
![image](https://github.com/bs-community/blessing-skin-server/assets/74001578/836217f2-25f3-4e95-980b-35982f4764c0)

**Comment by lizheyo77** [comment]
我也这样怎么解决的

**Comment by tnqzh123** [comment]
检查 pdo_mysql 扩展和 mysqli 扩展是否开启

**Comment by tnqzh123** [comment]
Issue closed due to inactivity (no response).
