### ISSUE TITLE
运行php artisan key:generate时报错（php：8.3.6)

### ISSUE THREAD

**Issue by xycabcd** [bs-community/blessing-skin-server#619]
### Blessing Skin 版本

6.0.2 / 6.0.0

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

None

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

如题
输出如下：

:/home/linuxbrew/.linuxbrew/blessing-skin-server$ php artisan key:generate

   TypeError

  Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, false given, called in /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98

  at vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928
    924▕      * @param array $lastErrors
    925▕      *
    926▕      * @return void
    927▕      */
  ➜ 928▕     private static function setLastErrors(array $lastErrors)
    929▕     {
    930▕         static::$lastErrors = $lastErrors;
    931▕     }
    932▕

   Whoops\Exception\ErrorException

  Using ${var} in strings is deprecated, use {$var} instead

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError(8192, 'Using ${var} in...', '/home/linuxbrew...', 52)
#1 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(571): include()
#2 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/linuxbrew...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(345): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Whoops\Exception\ErrorException))
#10 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Whoops\Exception\ErrorException))
#11 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(Whoops\Exception\Inspector))
#12 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#13 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle(Object(Whoops\Exception\ErrorException))
#14 [internal function]: Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#15 {main}
  thrown in /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52

   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError(8192, 'Using ${var} in...', '/home/linuxbrew...', 52)
#1 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(571): include()
#2 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/linuxbrew...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(345): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Whoops\Exception\ErrorException))
#10 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Whoops\Exception\ErrorException))
#11 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(Whoops\Exception\Inspector))
#12 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#13 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle(Object(Whoops\Exception\ErrorException))
#14 [internal function]: Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#15 {main}
  thrown

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }

   Whoops\Exception\ErrorException

  Using ${var} in strings is deprecated, use {$var} instead

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError(8192, 'Using ${var} in...', '/home/linuxbrew...', 52)
#1 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(571): include()
#2 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/linuxbrew...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(345): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Whoops\Exception\ErrorException))
#10 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Whoops\Exception\ErrorException))
#11 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(Whoops\Exception\Inspector))
#12 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#13 /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle(Object(Whoops\Exception\ErrorException))
#14 [internal function]: Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#15 {main}
  thrown in /home/linuxbrew/.linuxbrew/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52

### 重现步骤

WSL(Windows11),安装curl，安装linuxbrew(官方脚本），brew install httpd; brew install curl; brew install php 然后下载，Windows 下系统自带解压缩，到WSL共享文件夹。Linux内cd到该文件夹，执行命令

**Comment by xycabcd** [comment]
php版本问题，改为php8.1即可 
这个项目好长时间没更新了吧
