### ISSUE TITLE
启动器无法获取皮肤！

### ISSUE THREAD

**Issue by SS9G1145** [bs-community/blessing-skin-server#639]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

在使用PCL2启动器使用皮肤站启动时会显示无法获取皮肤！
![QQ123123](https://github.com/user-attachments/assets/d75e6d07-25eb-4c72-9098-c54b9c6ffcc1)

### 错误日志

```text
文件名：laravel-2024-08-02.log：
[2024-08-02 01:48:07] production.ERROR: Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known {"userId":7,"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known at /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:261)
[stacktrace]
#0 [internal function]: Swift_Transport_StreamBuffer->{closure}()
#1 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(264): stream_socket_client()
#2 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#3 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize()
#4 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Swift_Mailer->send()
#6 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(288): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#7 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(187): Illuminate\\Mail\\Mailer->send()
#8 /www/wwwroot/154.40.44.131/plugins/oauth-microsoft-live/vendor/illuminate/support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#9 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(188): Illuminate\\Mail\\Mailable->withLocale()
#10 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(304): Illuminate\\Mail\\Mailable->send()
#11 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(258): Illuminate\\Mail\\Mailer->sendMailable()
#12 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(124): Illuminate\\Mail\\Mailer->send()
#13 /www/wwwroot/154.40.44.131/app/Http/Controllers/UserController.php(163): Illuminate\\Mail\\PendingMail->send()
#14 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\UserController->sendVerificationEmail()
#15 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#16 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#17 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#19 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /www/wwwroot/154.40.44.131/plugins/single-player-limit/src/RequireBindPlayer.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): SinglePlayerLimit\\RequireBindPlayer->handle()
#22 /www/wwwroot/154.40.44.131/app/Http/Middleware/FireUserAuthenticated.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\FireUserAuthenticated->handle()
#24 /www/wwwroot/154.40.44.131/app/Http/Middleware/EnsureEmailFilled.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureEmailFilled->handle()
#26 /www/wwwroot/154.40.44.131/app/Http/Middleware/RejectBannedUser.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RejectBannedUser->handle()
#28 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#32 /www/wwwroot/154.40.44.131/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#34 /www/wwwroot/154.40.44.131/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#36 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#38 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /www/wwwroot/154.40.44.131/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /www/wwwroot/154.40.44.131/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#42 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#49 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#51 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#53 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /www/wwwroot/154.40.44.131/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#56 /www/wwwroot/154.40.44.131/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#58 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /www/wwwroot/154.40.44.131/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#61 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#62 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#64 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#65 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#67 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#69 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#70 /www/wwwroot/154.40.44.131/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#71 {main}
"} 
[2024-08-02 01:48:15] production.ERROR: Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known {"userId":7,"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known at /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:261)
[stacktrace]
#0 [internal function]: Swift_Transport_StreamBuffer->{closure}()
#1 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(264): stream_socket_client()
#2 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#3 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize()
#4 /www/wwwroot/154.40.44.131/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Swift_Mailer->send()
#6 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(288): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#7 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(187): Illuminate\\Mail\\Mailer->send()
#8 /www/wwwroot/154.40.44.131/plugins/oauth-microsoft-live/vendor/illuminate/support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#9 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(188): Illuminate\\Mail\\Mailable->withLocale()
#10 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(304): Illuminate\\Mail\\Mailable->send()
#11 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(258): Illuminate\\Mail\\Mailer->sendMailable()
#12 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(124): Illuminate\\Mail\\Mailer->send()
#13 /www/wwwroot/154.40.44.131/app/Http/Controllers/UserController.php(163): Illuminate\\Mail\\PendingMail->send()
#14 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\UserController->sendVerificationEmail()
#15 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#16 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#17 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#19 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /www/wwwroot/154.40.44.131/plugins/single-player-limit/src/RequireBindPlayer.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): SinglePlayerLimit\\RequireBindPlayer->handle()
#22 /www/wwwroot/154.40.44.131/app/Http/Middleware/FireUserAuthenticated.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\FireUserAuthenticated->handle()
#24 /www/wwwroot/154.40.44.131/app/Http/Middleware/EnsureEmailFilled.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureEmailFilled->handle()
#26 /www/wwwroot/154.40.44.131/app/Http/Middleware/RejectBannedUser.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RejectBannedUser->handle()
#28 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#32 /www/wwwroot/154.40.44.131/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#34 /www/wwwroot/154.40.44.131/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#36 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#38 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /www/wwwroot/154.40.44.131/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /www/wwwroot/154.40.44.131/plugins/oauth-microsoft-live/vendor/illuminate/session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#42 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#49 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#51 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#53 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /www/wwwroot/154.40.44.131/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#56 /www/wwwroot/154.40.44.131/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#58 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /www/wwwroot/154.40.44.131/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#61 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#62 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#64 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#65 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#67 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#69 /www/wwwroot/154.40.44.131/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#70 /www/wwwroot/154.40.44.131/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#71 {main}
"} 


文件名：mojang-verification.log：
[2024-08-01 22:14:59] production.INFO: User [3349033281@qq.com] is try to start verification  
[2024-08-01 22:18:48] production.INFO: User [3944912245@qq.com] is try to start verification  
[2024-08-01 22:23:51] production.INFO: User [2744084527@qq.com] is try to start verification  
[2024-08-01 22:25:00] production.INFO: User [2744084527@qq.com] is try to start verification  
[2024-08-01 22:37:06] production.INFO: User [3349033281@qq.com] is try to start verification  
[2024-08-01 22:37:12] production.INFO: User [3349033281@qq.com] is try to start verification  
[2024-08-01 22:39:19] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-01 22:42:22] production.INFO: User [3349033281@qq.com] is try to start verification  
[2024-08-01 22:43:47] production.INFO: User [3349033281@qq.com] is try to start verification  
[2024-08-02 01:47:12] production.INFO: User [784775291@qq.com] is try to start verification  
[2024-08-02 11:12:26] production.INFO: User [2499155002@qq.com] is try to start verification  
[2024-08-02 13:39:43] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:40:34] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:40:46] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:41:00] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:41:05] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:42:03] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:42:12] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:42:20] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 13:45:48] production.INFO: User [2943833230@qq.com] is try to start verification  
[2024-08-02 16:04:22] production.INFO: User [3349033281@qq.com] is try to start verification
```

### 重现步骤

所有玩家在登录时都会显示皮肤获取失败，第一次会显示错误，第二次就不显示了，在进入游戏后，皮肤无法正常显示

**Comment by xycabcd** [comment]
感觉像是未找到标识一类的错误

**Comment by SS9G1145** [comment]
已经解决了，感谢大佬！




韶山玖G壹壹肆伍
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bs-community/blessing-skin-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月8日(星期天) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bs-community/blessing-skin-server] 启动器无法获取皮肤！ (Issue #639)





 
感觉像是未找到标识一类的错误
