### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Shisuiicaro** [bs-community/blessing-skin-server#645]
### Which version of Blessing Skin are you using?

6.0

### Which version of PHP are you using?

8.1

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Which web server are you using?

None

### What happened?

Error 500 when trying to acess any page

### Error Logs

```text
[18-Sep-2024 09:11:00 Asia/Shanghai] PHP Fatal error:  Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, false given, called in /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98 and defined in /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928
Stack trace:
#0 /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(98): Carbon\Carbon::setLastErrors(false)
#1 /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(252): Carbon\Carbon->__construct(NULL, NULL)
#2 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php(37): Carbon\Carbon::now()
#3 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(317): Illuminate\Cache\FileStore->availableAt(0)
#4 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\Cache\FileStore->expiration(0)
#5 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\Cache\FileStore->put('yaml-trans-65cc...', Array, 0)
#6 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\Cache\FileStore->forever('yaml-trans-65cc...', Array)
#7 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(204): Illuminate\Cache\Repository->forever('yaml-trans-65cc...', Array)
#8 /home/shisuysb/public_html/app/Services/Translations/Yaml.php(27): Illuminate\Cache\Repository->put('yaml-trans-65cc...', Array)
#9 /home/shisuysb/public_html/app/Services/Translations/Loader.php(16): App\Services\Translations\Yaml->parse('/home/shisuysb/...')
#10 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php(67): App\Services\Translations\Loader->loadPath('/home/shisuysb/...', 'en', 'errors')
#11 /home/shisuysb/public_html/vendor/spatie/laravel-translation-loader/src/TranslationLoaderManager.php(21): Illuminate\Translation\FileLoader->load('en', 'errors', '*')
#12 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(263): Spatie\TranslationLoader\TranslationLoaderManager->load('en', 'errors', '*')
#13 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(190): Illuminate\Translation\Translator->load('*', 'errors', 'en')
#14 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(124): Illuminate\Translation\Translator->getLine('*', 'errors', 'en', 'exception.detai...', Array)
#15 /home/shisuysb/public_html/storage/framework/views/twig/74/74df88cb96372e9dfeb080e88dc2dbbf5703e6f1c88d247bcc9920be69564e48.php(61): Illuminate\Translation\Translator->get('errors.exceptio...', Array)
#16 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e2c01b4e56f11e129e560c86268357a4bd718777d93679ab7ba08aa1fa33801b->block_message(Array, Array)
#17 /home/shisuysb/public_html/storage/framework/views/twig/ba/ba2d783cc97ca379b23494034517ecd59f04ed4d1f0052c7a8baad0e63a01484.php(97): Twig\Template->displayBlock('message', Array, Array)
#18 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2051726433e6d9eb7d66f7d3595f4b6f8035945e7d5c4bf95ddd8fd5c9647c18->doDisplay(Array, Array)
#19 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /home/shisuysb/public_html/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\Template->display(Array, Array)
#21 /home/shisuysb/public_html/storage/framework/views/twig/74/74df88cb96372e9dfeb080e88dc2dbbf5703e6f1c88d247bcc9920be69564e48.php(43): TwigBridge\Twig\Template->display(Array, Array)
#22 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e2c01b4e56f11e129e560c86268357a4bd718777d93679ab7ba08aa1fa33801b->doDisplay(Array, Array)
#23 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /home/shisuysb/public_html/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\Template->display(Array, Array)
#25 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(390): TwigBridge\Twig\Template->display(Array)
#26 /home/shisuysb/public_html/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): Twig\Template->render(Array)
#27 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(139): TwigBridge\Engine\Twig->get('/home/shisuysb/...', Array)
#28 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#29 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#30 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()
#31 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#32 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\Http\Response->__construct(Object(Illuminate\View\View), 500, Array)
#33 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#34 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(582): Illuminate\Routing\ResponseFactory->view('errors::500', Array, 500, Array)
#35 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException))
#36 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException))
#37 /home/shisuysb/public_html/app/Exceptions/Handler.php(38): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(TypeError))
#38 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(TypeError))
#39 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(166): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(TypeError))
#40 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(TypeError))
#41 {main}
  thrown in /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 928
[18-Sep-2024 09:11:00 Asia/Shanghai] PHP Fatal error:  Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, false given, called in /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98 and defined in /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928
Stack trace:
#0 /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(98): Carbon\Carbon::setLastErrors(false)
#1 /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(252): Carbon\Carbon->__construct(NULL, NULL)
#2 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php(37): Carbon\Carbon::now()
#3 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(317): Illuminate\Cache\FileStore->availableAt(0)
#4 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\Cache\FileStore->expiration(0)
#5 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\Cache\FileStore->put('yaml-trans-65cc...', Array, 0)
#6 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\Cache\FileStore->forever('yaml-trans-65cc...', Array)
#7 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(204): Illuminate\Cache\Repository->forever('yaml-trans-65cc...', Array)
#8 /home/shisuysb/public_html/app/Services/Translations/Yaml.php(27): Illuminate\Cache\Repository->put('yaml-trans-65cc...', Array)
#9 /home/shisuysb/public_html/app/Services/Translations/Loader.php(16): App\Services\Translations\Yaml->parse('/home/shisuysb/...')
#10 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php(67): App\Services\Translations\Loader->loadPath('/home/shisuysb/...', 'en', 'errors')
#11 /home/shisuysb/public_html/vendor/spatie/laravel-translation-loader/src/TranslationLoaderManager.php(21): Illuminate\Translation\FileLoader->load('en', 'errors', '*')
#12 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(263): Spatie\TranslationLoader\TranslationLoaderManager->load('en', 'errors', '*')
#13 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(190): Illuminate\Translation\Translator->load('*', 'errors', 'en')
#14 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(124): Illuminate\Translation\Translator->getLine('*', 'errors', 'en', 'exception.detai...', Array)
#15 /home/shisuysb/public_html/storage/framework/views/twig/74/74df88cb96372e9dfeb080e88dc2dbbf5703e6f1c88d247bcc9920be69564e48.php(61): Illuminate\Translation\Translator->get('errors.exceptio...', Array)
#16 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e2c01b4e56f11e129e560c86268357a4bd718777d93679ab7ba08aa1fa33801b->block_message(Array, Array)
#17 /home/shisuysb/public_html/storage/framework/views/twig/ba/ba2d783cc97ca379b23494034517ecd59f04ed4d1f0052c7a8baad0e63a01484.php(97): Twig\Template->displayBlock('message', Array, Array)
#18 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2051726433e6d9eb7d66f7d3595f4b6f8035945e7d5c4bf95ddd8fd5c9647c18->doDisplay(Array, Array)
#19 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /home/shisuysb/public_html/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\Template->display(Array, Array)
#21 /home/shisuysb/public_html/storage/framework/views/twig/74/74df88cb96372e9dfeb080e88dc2dbbf5703e6f1c88d247bcc9920be69564e48.php(43): TwigBridge\Twig\Template->display(Array, Array)
#22 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e2c01b4e56f11e129e560c86268357a4bd718777d93679ab7ba08aa1fa33801b->doDisplay(Array, Array)
#23 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /home/shisuysb/public_html/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\Template->display(Array, Array)
#25 /home/shisuysb/public_html/vendor/twig/twig/src/Template.php(390): TwigBridge\Twig\Template->display(Array)
#26 /home/shisuysb/public_html/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): Twig\Template->render(Array)
#27 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(139): TwigBridge\Engine\Twig->get('/home/shisuysb/...', Array)
#28 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#29 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#30 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()
#31 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#32 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\Http\Response->__construct(Object(Illuminate\View\View), 500, Array)
#33 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#34 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(582): Illuminate\Routing\ResponseFactory->view('errors::500', Array, 500, Array)
#35 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException))
#36 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException))
#37 /home/shisuysb/public_html/app/Exceptions/Handler.php(38): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#38 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#39 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(166): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#40 /home/shisuysb/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(200): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#41 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#42 {main}
  thrown in /home/shisuysb/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 928
```

### Steps to Reproduce

- Dowload blessing skin 6.0

**Comment by xycabcd** [comment]
这项目已经基本死了。Maintainers都没动静了，有问题只能找别的会php的人修了

**Comment by tnqzh123** [comment]
> 这项目已经基本死了。Maintainers都没动静了，有问题只能找别的会php的人修了

?

**Comment by mochaaP** [comment]
> 这项目已经基本死了。Maintainers都没动静了，有问题只能找别的会php的人修了

?

**Comment by xycabcd** [comment]
各位Maintainers都还在关注项目那就太好了!
